name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Install sbt
      run: |
        echo "Installing sbt..."
        curl -L -o sbt.zip https://github.com/sbt/sbt/releases/download/v1.5.5/sbt-1.5.5.zip
        unzip sbt.zip
        sudo mv sbt /usr/local/sbt
        sudo ln -s /usr/local/sbt/bin/sbt /usr/local/bin/sbt
        sudo ln -s /usr/local/sbt/bin/sbtn /usr/local/bin/sbtn
    - name: Run tests
      run: sbt test